// This file is auto-generated by scripts/gen-db-meta.mjs. Do not edit manually.

export type FieldMeta =
  | {kind: 'string' | 'number' | 'boolean' | 'int64' | 'bytes' | 'null'; optional: boolean}
  | {kind: 'id'; table: string; optional: boolean}
  | {kind: 'enum'; valueType: 'string' | 'number' | 'boolean'; values: Array<string | number | boolean>; optional: boolean}
  | {kind: 'literal'; valueType: 'string' | 'number' | 'boolean'; values: Array<string | number | boolean>; optional: boolean}
  | {kind: 'array'; of: FieldMeta; optional: boolean}
  | {kind: 'object'; fields: Record<string, FieldMeta>; optional: boolean}
  | {kind: 'union'; options: FieldMeta[]; optional: boolean}
  | {kind: 'record'; optional: boolean}
  | {kind: 'unknown'; source: string; optional: boolean}

export const dbMeta = {
  "demo": {
    fields: {
      "username": {"kind":"string","optional":false},
    },
  },
} as const

export type DbMeta = typeof dbMeta
export type DbTableName = keyof DbMeta & string
export type DbTableMeta<T extends DbTableName> = DbMeta[T]
