// This file is auto-generated by scripts/gen-db-meta.mjs. Do not edit manually.

import {api} from '@/lib/convex'
import type {TableNames} from '@convex/_generated/dataModel'

export const dbTables = ["demo", "concepts"] as const
export type DbTable = (typeof dbTables)[number]

export const dbAdminApi = {
  "demo": {
    length: api.tables.demo.length,
    list: api.tables.demo.list,
    getById: api.tables.demo.getById,
    create: api.tables.demo.create,
    update: api.tables.demo.update,
    remove: api.tables.demo.remove,
  },
  "concepts": {
    length: api.tables.concepts.length,
    list: api.tables.concepts.list,
    getById: api.tables.concepts.getById,
    create: api.tables.concepts.create,
    update: api.tables.concepts.update,
    remove: api.tables.concepts.remove,
  },
} as const satisfies Record<
  DbTable,
  {
    length: unknown
    list: unknown
    getById: unknown
    create: unknown
    update: unknown
    remove: unknown
  }
>

export function isDbTable(slug: string): slug is DbTable {
  return (dbTables as readonly string[]).includes(slug)
}

export function assertDbTable(slug: string): DbTable {
  if (!isDbTable(slug)) throw new Error('Unknown table: ' + slug)
  return slug
}

// Type-level check that generated names are valid Convex table names.
// (Not used at runtime.)
export type _DbTableNamesCheck = DbTable extends TableNames ? true : never
