import {Elysia, t} from 'elysia'

import {isAiAccessAllowed} from '@/api/lib/access-gate'
import {completionForSingleModel, getRankedFreeTextModels, OpenRouterHttpError, requestFreeModelChatCompletion, requestFreeModelChatCompletionStream} from '@/api/lib/openrouter'

const getQuerySchema = t.Object({
  refresh: t.Optional(t.String()),
})

const getModelsQuerySchema = t.Object({
  refresh: t.Optional(t.String()),
  limit: t.Optional(t.String()),
})

const getFullModelsQuerySchema = t.Object({
  refresh: t.Optional(t.String()),
  limit: t.Optional(t.String()),
})

const postBodySchema = t.Object({
  prompt: t.String({minLength: 1, maxLength: 12_000}),
  model: t.Optional(t.String()),
  system: t.Optional(t.String({maxLength: 2_000})),
  temperature: t.Optional(t.Number({minimum: 0, maximum: 2})),
  maxTokens: t.Optional(t.Number({minimum: 32, maximum: 262_144})),
})

const streamBodySchema = postBodySchema

const probeBodySchema = t.Object({
  prompt: t.String({minLength: 1, maxLength: 6_000}),
  maxConcurrency: t.Optional(t.Number({minimum: 1, maximum: 12})),
})

const MAX_PROMPT_CHARS = 6_000
const MAX_SYSTEM_CHARS = 2_000
const RATE_LIMIT_WINDOW_MS = 60_000
const RATE_LIMIT_MAX_REQUESTS = 18
const RATE_LIMIT_MIN_INTERVAL_MS = 1_200
const RATE_LIMIT_BLOCK_MS = 12_000
const RATE_LIMIT_MAX_IN_FLIGHT = 2

type ClientRateState = {
  timestamps: number[]
  lastRequestAt: number
  blockedUntil: number
  inFlight: number
}

const clientRateState = new Map<string, ClientRateState>()

function toJsonError(status: number, message: string, meta?: Record<string, unknown>) {
  return new Response(
    JSON.stringify({
      ok: false,
      message,
      meta,
    }),
    {
      status,
      headers: {'content-type': 'application/json; charset=utf-8'},
    },
  )
}

function toBool(value: string | undefined) {
  if (!value) return false
  return value === '1' || value.toLowerCase() === 'true'
}

function toSseEvent(event: string, payload: Record<string, unknown>) {
  return `event: ${event}\ndata: ${JSON.stringify(payload)}\n\n`
}

type ModelAttemptErrorLite = {model: string; status: number; message: string}

function truncateForNotice(text: string, maxChars: number) {
  const normalized = text.replace(/\s+/g, ' ').trim()
  if (normalized.length <= maxChars) return normalized
  return `${normalized.slice(0, maxChars - 1)}…`
}

/**
 * Explains when the client asked for one free model but another actually answered
 * (automatic fallback after errors, overload, or missing model id).
 */
function buildModelRoutingNotice(params: {requestedModel?: string; actualModel: string; usedFallback: boolean; freeModelIds: Set<string>; attemptErrors?: ModelAttemptErrorLite[]}): string | undefined {
  const {requestedModel, actualModel, usedFallback, freeModelIds, attemptErrors} = params
  const firstFail = attemptErrors?.[0]

  if (requestedModel && !freeModelIds.has(requestedModel)) {
    return `Requested model "${requestedModel}" is not in the current free model list; "${actualModel}" was used instead.`
  }

  if (!usedFallback) return undefined

  if (requestedModel && requestedModel !== actualModel) {
    const detail = firstFail ? ` First error from "${firstFail.model}": ${truncateForNotice(firstFail.message, 140)}.` : ''
    return `You selected "${requestedModel}", but this reply was generated by "${actualModel}".${detail} Other free models are tried automatically when the preferred one is busy or returns an error.`
  }

  if (firstFail) {
    return `Earlier models in the fallback chain failed (${truncateForNotice(firstFail.message, 120)}); response is from "${actualModel}".`
  }

  return undefined
}

function parseLimit(raw: string | undefined, fallback: number, max: number) {
  if (!raw) return fallback
  const parsed = Number(raw)
  if (!Number.isFinite(parsed)) return fallback
  return Math.min(max, Math.max(1, Math.floor(parsed)))
}

function getClientKey(request: Request) {
  const xForwardedFor = request.headers.get('x-forwarded-for')
  if (xForwardedFor) return xForwardedFor.split(',')[0]?.trim() || 'unknown'

  const cloudflareIp = request.headers.get('cf-connecting-ip')
  if (cloudflareIp) return cloudflareIp

  const realIp = request.headers.get('x-real-ip')
  if (realIp) return realIp

  return 'unknown'
}

function beginAiRequestGuard(params: {request: Request; prompt: string; system?: string}) {
  const now = Date.now()
  const promptLength = params.prompt.length
  const systemLength = params.system?.length ?? 0
  const clientKey = getClientKey(params.request)

  if (promptLength > MAX_PROMPT_CHARS) {
    return {
      ok: false as const,
      response: toJsonError(413, `Prompt is too long. Max ${MAX_PROMPT_CHARS} characters.`, {promptLength, maxPromptLength: MAX_PROMPT_CHARS}),
    }
  }

  if (systemLength > MAX_SYSTEM_CHARS) {
    return {
      ok: false as const,
      response: toJsonError(413, `System prompt is too long. Max ${MAX_SYSTEM_CHARS} characters.`, {systemLength, maxSystemLength: MAX_SYSTEM_CHARS}),
    }
  }

  const state = clientRateState.get(clientKey) ?? {
    timestamps: [],
    lastRequestAt: 0,
    blockedUntil: 0,
    inFlight: 0,
  }

  state.timestamps = state.timestamps.filter((timestamp) => now - timestamp <= RATE_LIMIT_WINDOW_MS)

  if (state.blockedUntil > now) {
    return {
      ok: false as const,
      response: toJsonError(429, 'Too many requests. Please wait a few seconds and retry.', {
        retryAfterMs: state.blockedUntil - now,
        windowMs: RATE_LIMIT_WINDOW_MS,
      }),
    }
  }

  if (now - state.lastRequestAt < RATE_LIMIT_MIN_INTERVAL_MS) {
    state.blockedUntil = now + RATE_LIMIT_BLOCK_MS
    clientRateState.set(clientKey, state)
    return {
      ok: false as const,
      response: toJsonError(429, 'Requests are too frequent. Slow down a bit.', {
        retryAfterMs: RATE_LIMIT_BLOCK_MS,
        minIntervalMs: RATE_LIMIT_MIN_INTERVAL_MS,
      }),
    }
  }

  if (state.timestamps.length >= RATE_LIMIT_MAX_REQUESTS) {
    state.blockedUntil = now + RATE_LIMIT_BLOCK_MS
    clientRateState.set(clientKey, state)
    return {
      ok: false as const,
      response: toJsonError(429, 'Rate limit exceeded. Try again shortly.', {
        retryAfterMs: RATE_LIMIT_BLOCK_MS,
        maxRequests: RATE_LIMIT_MAX_REQUESTS,
        windowMs: RATE_LIMIT_WINDOW_MS,
      }),
    }
  }

  if (state.inFlight >= RATE_LIMIT_MAX_IN_FLIGHT) {
    return {
      ok: false as const,
      response: toJsonError(429, 'Too many active AI requests from this client.', {
        maxInFlight: RATE_LIMIT_MAX_IN_FLIGHT,
      }),
    }
  }

  state.timestamps.push(now)
  state.lastRequestAt = now
  state.inFlight += 1
  clientRateState.set(clientKey, state)

  let released = false
  const release = () => {
    if (released) return
    released = true

    const current = clientRateState.get(clientKey)
    if (!current) return

    current.inFlight = Math.max(0, current.inFlight - 1)
    current.timestamps = current.timestamps.filter((timestamp) => Date.now() - timestamp <= RATE_LIMIT_WINDOW_MS)

    const stale = current.inFlight === 0 && current.timestamps.length === 0 && Date.now() - current.lastRequestAt > RATE_LIMIT_WINDOW_MS
    if (stale) {
      clientRateState.delete(clientKey)
      return
    }

    clientRateState.set(clientKey, current)
  }

  return {
    ok: true as const,
    release,
  }
}

function toMinimalModel(model: {rank: number; id: string; name: string}) {
  return {
    rank: model.rank,
    id: model.id,
    name: model.name,
  }
}

function toDetailedModel(model: {rank: number; id: string; name: string; contextLength: number; maxCompletionTokens: number}) {
  return {
    rank: model.rank,
    id: model.id,
    name: model.name,
    contextLength: model.contextLength,
    maxOutputTokens: model.maxCompletionTokens,
  }
}

function toFullModel(model: Awaited<ReturnType<typeof getRankedFreeTextModels>>['models'][number]) {
  return {
    rank: model.rank,
    score: model.score,
    id: model.id,
    name: model.name,
    description: model.description,
    contextLength: model.contextLength,
    maxOutputTokens: model.maxCompletionTokens,
    createdAt: model.createdAt,
    modality: model.modality,
    modalities: model.modalities,
    pricing: model.pricing,
  }
}

function buildGuide(origin: string, payload: Awaited<ReturnType<typeof getRankedFreeTextModels>>) {
  const resolve = (path: string) => `${origin}${path}`
  const defaultModel = payload.models[0]?.id
  const topRecommended = payload.models.slice(0, 15).map(toMinimalModel)

  return {
    endpoint: 'ai' as const,
    version: 2,
    provider: 'openrouter',
    url: resolve('/api/ai'),
    modelsUrl: resolve('/api/ai/models'),
    fullModelsUrl: resolve('/api/models'),
    defaults: {
      model: defaultModel,
      temperature: 0.6,
      maxTokens: 1_024,
    },
    topRecommendedModels: topRecommended,
    meta: {
      topCount: topRecommended.length,
      freeModelCount: payload.models.length,
      fetchedAt: payload.fetchedAt,
      stale: payload.stale,
    },
    usage: {
      get: {
        method: 'GET',
        url: resolve('/api/ai'),
        description: 'Returns this guide and current free text model ranking.',
      },
      post: {
        method: 'POST',
        url: resolve('/api/ai'),
        body: {
          prompt: 'string (required)',
          model: 'string (optional, must be in models list)',
          system: 'string (optional)',
          temperature: 'number 0..2 (optional)',
          maxTokens: 'number 32..262144 (optional)',
        },
        sampleBody: {
          prompt: 'why tailwindcss is better then css?',
          model: defaultModel,
        },
      },
      stream: {
        method: 'POST',
        url: resolve('/api/ai/stream'),
        body: {
          prompt: 'string (required)',
          model: 'string (optional)',
          system: 'string (optional)',
          temperature: 'number 0..2 (optional)',
          maxTokens: 'number 32..262144 (optional)',
        },
        description: 'SSE stream with token-by-token output for realtime chat UI.',
      },
      models: {
        method: 'GET',
        url: resolve('/api/ai/models'),
        description: 'Returns compact ranked list of free text models for UI/selection.',
      },
      fullModels: {
        method: 'GET',
        url: resolve('/api/models'),
        description: 'Returns full model metadata for each ranked free text model.',
      },
      note: 'Uses only free OpenRouter text models. If the chosen model errors or is overloaded, the server tries other ranked free models. Check `usedFallback`, `requestedModel`, `model`, and `warning` on JSON responses or in SSE `meta` / `done` events.',
    },
  }
}

/**
 * AI endpoint backed by OpenRouter free models.
 *
 * - GET `/api/ai` returns guide + ranked list of free text models.
 * - POST `/api/ai` returns model completion for `{prompt, model?}`.
 *
 * When `ACCESS_KEY` is set, all routes here require `isAiAccessAllowed` (see `access-gate.ts`).
 */
const aiRoutes = new Elysia()
  .onBeforeHandle(async ({request, set}) => {
    if (!(await isAiAccessAllowed(request))) {
      set.status = 401
      return {
        ok: false,
        message:
          'Unauthorized. When ACCESS_KEY is set, send header X-Access-Key or Authorization: Bearer with that value, or use a valid access-token cookie (open /ai?key=… once).',
      }
    }
  })
  .get(
      '/ai',
      async ({query, request, set}) => {
        set.headers['cache-control'] = 'no-store, no-cache, max-age=0, must-revalidate'
        set.headers.pragma = 'no-cache'

        const forceRefresh = toBool(query.refresh)
        const ranked = await getRankedFreeTextModels({forceRefresh})
        const origin = new URL(request.url).origin

        return buildGuide(origin, ranked)
      },
      {
        query: getQuerySchema,
        response: t.Any(),
        detail: {
          summary: 'AI guide and free models',
          description: 'Returns compact endpoint tutorial and top recommended free OpenRouter models.',
          operationId: 'getAiGuide',
        },
      },
    )
    .get(
      '/ai/models',
      async ({query, set}) => {
        set.headers['cache-control'] = 'no-store, no-cache, max-age=0, must-revalidate'
        set.headers.pragma = 'no-cache'

        const forceRefresh = toBool(query.refresh)
        const limit = parseLimit(query.limit, 15, 50)
        const ranked = await getRankedFreeTextModels({forceRefresh})
        const models = ranked.models.slice(0, limit).map(toDetailedModel)

        return {
          ok: true,
          defaults: {
            model: ranked.models[0]?.id,
          },
          models,
          meta: {
            returned: models.length,
            total: ranked.models.length,
            fetchedAt: ranked.fetchedAt,
            stale: ranked.stale,
          },
        }
      },
      {
        query: getModelsQuerySchema,
        response: t.Any(),
        detail: {
          summary: 'Ranked free model list',
          description: 'Returns the best free OpenRouter text models with minimal useful metadata.',
          operationId: 'getAiModels',
        },
      },
    )
    .get(
      '/models',
      async ({query, set}) => {
        set.headers['cache-control'] = 'no-store, no-cache, max-age=0, must-revalidate'
        set.headers.pragma = 'no-cache'

        const forceRefresh = toBool(query.refresh)
        const ranked = await getRankedFreeTextModels({forceRefresh})
        const limit = parseLimit(query.limit, ranked.models.length, 300)
        const models = ranked.models.slice(0, limit).map(toFullModel)

        return {
          ok: true,
          models,
          meta: {
            returned: models.length,
            total: ranked.models.length,
            fetchedAt: ranked.fetchedAt,
            stale: ranked.stale,
          },
        }
      },
      {
        query: getFullModelsQuerySchema,
        response: t.Any(),
        detail: {
          summary: 'Full ranked model list',
          description: 'Returns full metadata for each free OpenRouter text model.',
          operationId: 'getFullModels',
        },
      },
    )
    .post(
      '/ai/probe-all',
      async ({body, request, set}) => {
        set.headers['cache-control'] = 'no-store, no-cache, max-age=0, must-revalidate'
        set.headers.pragma = 'no-cache'

        const prompt = body.prompt.trim()
        if (!prompt) return toJsonError(400, 'Missing or empty prompt.')

        const guard = beginAiRequestGuard({request, prompt, system: undefined})
        if (!guard.ok) return guard.response

        const maxConcurrency = Math.min(12, Math.max(1, Math.floor(body.maxConcurrency ?? 6)))
        const outputMaxChars = 180
        const errorMaxChars = 220

        try {
          const ranked = await getRankedFreeTextModels()
          if (!ranked.models.length) {
            return toJsonError(503, 'No free models available from OpenRouter right now.')
          }

          const models = ranked.models.map((m) => ({id: m.id, rank: m.rank, name: m.name}))
          const results: Array<{
            model: string
            name: string
            rank: number
            ok: boolean
            output?: string
            error?: string
            status?: number
            latencyMs: number
          }> = []

          for (let i = 0; i < models.length; i += maxConcurrency) {
            const batch = models.slice(i, i + maxConcurrency)
            const part = await Promise.all(
              batch.map(async ({id, rank, name}) => {
                const started = Date.now()
                try {
                  const out = await completionForSingleModel({
                    model: id,
                    prompt,
                    maxTokens: 96,
                    temperature: 0.2,
                  })
                  const text = out.text.replace(/\s+/g, ' ').trim()
                  const snippet = text.length > outputMaxChars ? `${text.slice(0, outputMaxChars - 1)}…` : text
                  return {
                    model: id,
                    name,
                    rank,
                    ok: true,
                    output: snippet,
                    latencyMs: Date.now() - started,
                  }
                } catch (error) {
                  const status = error instanceof OpenRouterHttpError ? error.status : 500
                  const raw = error instanceof Error ? error.message : typeof error === 'string' ? error : 'Request failed.'
                  const err = raw.length > errorMaxChars ? `${raw.slice(0, errorMaxChars - 1)}…` : raw
                  return {
                    model: id,
                    name,
                    rank,
                    ok: false,
                    error: err,
                    status,
                    latencyMs: Date.now() - started,
                  }
                }
              }),
            )
            results.push(...part)
          }

          results.sort((a, b) => a.rank - b.rank)

          return {
            ok: true,
            prompt,
            total: results.length,
            maxConcurrency,
            results,
            meta: {
              fetchedAt: ranked.fetchedAt,
              stale: ranked.stale,
            },
          }
        } catch (error) {
          if (error instanceof OpenRouterHttpError) {
            return toJsonError(error.status, error.message, {
              source: 'openrouter',
              details: error.payload,
            })
          }

          if (error instanceof Error) {
            return toJsonError(500, error.message, {source: 'ai-endpoint'})
          }

          return toJsonError(500, 'Unknown probe failure.', {source: 'ai-endpoint'})
        } finally {
          guard.release()
        }
      },
      {
        body: probeBodySchema,
        response: t.Any(),
        detail: {
          summary: 'Probe all free models',
          description: 'Runs a short completion against every ranked free model in concurrent batches (smoke test).',
          operationId: 'postAiProbeAll',
        },
      },
    )
    .post(
      '/ai',
      async ({body, request, set}) => {
        set.headers['cache-control'] = 'no-store, no-cache, max-age=0, must-revalidate'
        set.headers.pragma = 'no-cache'

        const prompt = body.prompt.trim()
        const system = body.system?.trim() || undefined

        if (!prompt) return toJsonError(400, 'Missing or empty prompt.')

        const guard = beginAiRequestGuard({request, prompt, system})
        if (!guard.ok) return guard.response

        try {
          const ranked = await getRankedFreeTextModels()
          const freeModelIds = new Set(ranked.models.map((model) => model.id))
          const requestedModel = body.model?.trim()

          const completion = await requestFreeModelChatCompletion({
            prompt,
            requestedModel,
            system,
            temperature: body.temperature,
            maxTokens: body.maxTokens,
          })

          const warning = buildModelRoutingNotice({
            requestedModel,
            actualModel: completion.model,
            usedFallback: completion.usedFallback,
            freeModelIds,
            attemptErrors: completion.attemptErrors,
          })

          return {
            ok: true,
            output: completion.text,
            model: completion.model,
            requestedModel: completion.requestedModel,
            usedFallback: completion.usedFallback,
            attemptedModels: completion.attemptedModels,
            attemptErrors: completion.attemptErrors,
            usage: completion.usage,
            warning,
          }
        } catch (error) {
          if (error instanceof OpenRouterHttpError) {
            return toJsonError(error.status, error.message, {
              source: 'openrouter',
              details: error.payload,
            })
          }

          if (error instanceof Error) {
            return toJsonError(500, error.message, {source: 'ai-endpoint'})
          }

          return toJsonError(500, 'Unknown AI endpoint failure.', {source: 'ai-endpoint'})
        } finally {
          guard.release()
        }
      },
      {
        body: postBodySchema,
        response: t.Any(),
        detail: {
          summary: 'Generate AI completion',
          description: 'Returns model response from OpenRouter free models, with automatic fallback on failures.',
          operationId: 'postAiCompletion',
        },
      },
    )
    .post(
      '/ai/stream',
      async ({body, request}) => {
        const prompt = body.prompt.trim()
        const system = body.system?.trim() || undefined

        if (!prompt) return toJsonError(400, 'Missing or empty prompt.')

        const guard = beginAiRequestGuard({request, prompt, system})
        if (!guard.ok) return guard.response

        const encoder = new TextEncoder()

        const stream = new ReadableStream<Uint8Array>({
          start(controller) {
            void (async () => {
              try {
                const ranked = await getRankedFreeTextModels()
                const freeModelIds = new Set(ranked.models.map((model) => model.id))
                const requestedModel = body.model?.trim()

                const streamResult = await requestFreeModelChatCompletionStream({
                  prompt,
                  requestedModel,
                  system,
                  temperature: body.temperature,
                  maxTokens: body.maxTokens,
                })

                const routingWarning = (actualModel: string) =>
                  buildModelRoutingNotice({
                    requestedModel,
                    actualModel,
                    usedFallback: streamResult.usedFallback,
                    freeModelIds,
                    attemptErrors: streamResult.attemptErrors,
                  })

                controller.enqueue(
                  encoder.encode(
                    toSseEvent('meta', {
                      model: streamResult.model,
                      requestedModel: streamResult.requestedModel,
                      usedFallback: streamResult.usedFallback,
                      attemptedModels: streamResult.attemptedModels,
                      attemptErrors: streamResult.attemptErrors,
                      warning: routingWarning(streamResult.model),
                    }),
                  ),
                )

                let output = ''
                let reasoningOutput = ''
                let model = streamResult.model
                let usage: {promptTokens?: number; completionTokens?: number; totalTokens?: number} | undefined

                for await (const chunk of streamResult.stream) {
                  if (chunk.error?.message) {
                    throw new OpenRouterHttpError(chunk.error.message, 502, chunk.error)
                  }

                  if (chunk.model) model = chunk.model
                  if (chunk.usage) {
                    usage = {
                      promptTokens: chunk.usage.promptTokens,
                      completionTokens: chunk.usage.completionTokens,
                      totalTokens: chunk.usage.totalTokens,
                    }
                  }

                  for (const choice of chunk.choices ?? []) {
                    const d = choice.delta
                    const content = typeof d?.content === 'string' ? d.content : ''
                    const reasoning = typeof d?.reasoning === 'string' ? d.reasoning : ''
                    if (content) {
                      output += content
                      controller.enqueue(encoder.encode(toSseEvent('token', {text: content})))
                    }
                    if (reasoning) {
                      reasoningOutput += reasoning
                      controller.enqueue(encoder.encode(toSseEvent('reasoning', {text: reasoning})))
                    }
                  }
                }

                controller.enqueue(
                  encoder.encode(
                    toSseEvent('done', {
                      output,
                      reasoning: reasoningOutput.trim() || undefined,
                      model,
                      requestedModel: streamResult.requestedModel,
                      usedFallback: streamResult.usedFallback,
                      attemptedModels: streamResult.attemptedModels,
                      attemptErrors: streamResult.attemptErrors,
                      warning: routingWarning(model),
                      usage,
                    }),
                  ),
                )
              } catch (error) {
                const message = error instanceof Error ? error.message : 'Unknown stream failure.'
                controller.enqueue(encoder.encode(toSseEvent('error', {message})))
              } finally {
                guard.release()
                controller.close()
              }
            })()
          },
          cancel() {
            guard.release()
          },
        })

        return new Response(stream, {
          status: 200,
          headers: {
            'content-type': 'text/event-stream; charset=utf-8',
            'cache-control': 'no-store, no-cache, must-revalidate, max-age=0',
            connection: 'keep-alive',
            'x-accel-buffering': 'no',
          },
        })
      },
      {
        body: streamBodySchema,
        response: t.Any(),
        detail: {
          summary: 'Stream AI completion (SSE)',
          description: 'Streams model output token-by-token over Server-Sent Events.',
          operationId: 'postAiCompletionStream',
        },
      },
    )

export const AiEndpoint = <Prefix extends string>(app: Elysia<Prefix>) => app.use(aiRoutes)
